### ISSUE TITLE
Add settings button

### ISSUE THREAD

**Issue by tigran-saatchyan** [tigran-saatchyan/StockTic#12]
- [ ] tigran-saatchyan/StockTic#10
- [ ] tigran-saatchyan/StockTic#9
- [ ] tigran-saatchyan/StockTic#8
- [ ] tigran-saatchyan/StockTic#7
- [ ] tigran-saatchyan/StockTic#6
