### ISSUE TITLE
Telegram Bot for stock

### ISSUE THREAD

**Issue by tigran-saatchyan** [tigran-saatchyan/StockTic#19]
- [x] tigran-saatchyan/investment-bot#2
- [ ] tigran-saatchyan/StockTic#18
- [x] tigran-saatchyan/investment-bot#4
- [x] tigran-saatchyan/investment-bot#5
- [ ] tigran-saatchyan/StockTic#17
- [x] tigran-saatchyan/investment-bot#7
- [ ] tigran-saatchyan/StockTic#16
- [ ] tigran-saatchyan/StockTic#15
- [ ] tigran-saatchyan/StockTic#14
- [ ] tigran-saatchyan/StockTic#13
